---
# tasks file for pre-docker
#

- name: garatindo os pacotes principais
  package:
    name: 
        - docker-ce
        - nginx
        - python-pip

- name: install docker-py
  pip:
    name: docker-py

- name: garantindo servicos nginx e docker
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - docker
